### PR TITLE
mod `StrBuf::and` ret type: Ret Option<StrBuf>

### PR DESCRIPTION
**Pull request by NobodyXu**
Return None if the StrBuf isn't large enough.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Why it is needed?
Once panic const fn will be stable I'll improve error message, but until then `const fn and` should panic.
If you want to check it at runtime you should use `push_str` methpd

**Comment by NobodyXu** [comment]
Ok, it seems that I misunderstood the intention of your API.

**Comment by DoumanAsh** [comment]
NP.
Just to clarify `StrBuf::and` is intended for `const fn` context.
Otherwise you do not benefit from it and better use `StrBuf::push_str` which returns number of written bytes.

**Comment by NobodyXu** [comment]
Got it.

Thanks.

**Pull request closed without merging**
